# Generated by Django 5.0.3 on 2024-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[('superuser', 'Superuser'), ('adminuser', 'Adminuser'), ('student', 'Student')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
