# Generated by Django 5.0.3 on 2024-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usermaster_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='isactive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('adminuser', 'Adminuser'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
