# Generated by Django 5.0.3 on 2024-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_usermaster_created_at_alter_usermaster_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
